name: Deploy Laravel to VPS

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Install Dependencies
              run: |
                  sudo dnf update -y
                  sudo dnf install -y php-cli php-xml php-json php-fpm composer git
                  composer install --no-dev --prefer-dist --optimize-autoloader
                  php artisan config:cache
                  php artisan route:cache
                  php artisan view:cache

            - name: Deploy Application via SSH
              run: |
                  ssh -o StrictHostKeyChecking=no root@your_vps_ip_address << 'EOF'
                    cd /var/www/sportsync
                    git pull origin main
                    composer install --no-dev --prefer-dist --optimize-autoloader
                    php artisan migrate --force
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache
                    sudo systemctl restart php-fpm
                    sudo systemctl restart nginx
                  EOF
